export const types = {
  SET_LIVE_HISTORY: 'SET_LIVE_HISTORY',
  GET_LIVE_HISTORY: 'GET_LIVE_HISTORY',
  SET_LIVE_PROGRESS: 'SET_LIVE_PROGRESS',
  GET_LIVE_PROGRESS: 'GET_LIVE_PROGRESS',
  SET_LIVE_TV: 'SET_LIVE_TV',
  GET_LIVE_TV: 'GET_LIVE_TV',
}
