export const types = {
    DEFAULT:        'DEFAULT',
    SET_SETTINGS:   'SET_SETTINGS',
    GET_SETTINGS:   'GET_SETTINGS',
    SET_GAME:       'SET_GAME',
    GET_GAME:       'GET_GAME',
    SET_BETSLIP:    'SET_BETSLIP',
    GET_BETSLIP:    'GET_BETSLIP',
    DELETE_BETSLIP: 'DELETE_BETSLIP'
};
