export const SET_SPORT = "SET_SPORT"
export const GET_SPORT = "GET_SPORT"
export const SET_CATEGORY = "SET_CATEGORY"
export const GET_CATEGORY = "GET_CATEGORY"
export const SET_URL = "SET_URL"
export const GET_URL = "GET_URL"
export const SET_LEAGUE = "SET_LEAGUE"
export const GET_LEAGUE = "GET_LEAGUE"
